INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bobó de camarão', '1 colher (sopa)', 46, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Canja', '1 concha', 110, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cuscuz à paulista', '1 fatia média (100 g)', 328, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Dobradinha', '1 colher (sopa)', 39, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Feijoada', '1 concha', 346, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Goulash', '1 colher grande (90 g)', 186, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Moqueca de camarão', '1 concha', 320, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Moqueca de peixe', '1 concha', 290, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Paella', '1 colher grande (90 g)', 180, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pimentão assado recheado com carne moída', '1 unidade (200 g)', 298, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Risoto de frango', '1 colher (sopa)', 63, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Risoto de funghi', '1 colher (sopa)', 78, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salpicão de frango', '1 colher (sopa)', 47, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Suflê de espinafre', '1 colher (sopa)', 45, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Suflê de legumes', '1 colher (sopa)', 38, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Suflê de queijo', '1 colher (sopa)', 55, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Vatapá', '1 colher grande (90 g)', 320, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Yakissoba', '1 colher grande (75 g)', 112, 13);