INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Atum em óleo', '1 lata (160 g)', 448, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Atum em água', '1 lata (160 g)', 184, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bacalhau assado', '1 posta (100 g)', 110, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Camarão cozido', '5 grandes(100 g)', 82, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Camarão frito', '10 médios (100 g)', 310, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Estrogonofe de camarão', '1 concha', 338, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Filé de peixe grelhado', '1 médio (120 g)', 120, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Filé de peixe à milanesa e molho de camarão', '1 médio (100g)', 383, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Kani kama', '1 stick (16 g)', 13, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lagosta grelhada na manteiga', '1 unidade (200 g)', 308, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lula cozida', '1/2 concha (100 g)', 93, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lula frita', '4 colheres (sopa) (100 g)', 190, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mariscos ao vinagrete', '1 prato (sobremesa) ', 82, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mexilhão cozido', '8 grandes (100 g)', 80, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ostras', '6 médias (100 g)', 60, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Peixe à escabeche', '1 filé médio (100 g)', 183, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Peixe ensopado', '1 concha (100 g)', 130, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pintado na brasa', '1 pedaço médio (80 g)', 134, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Polvo refogado', '1 colher (sopa) (22 g)', 18, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salmão defumado', '1 filé fino (50 g)', 75, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salmão cozido ou grelhado ', '1 filé (120 g)', 240, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sardinha em conserva (molho de tomate)', '1 unidade (25 g)', 45, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sardinha (no azeite)', '1 unidade (33 g)', 98, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sardinha frita', '1 unidade (40 g)', 91, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sashimi (variado)', '1 porção (100 g)', 80, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Truta assada ou cozida', '1/2 unidade (120 g)', 162, 4);