INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Abacate', '1/2 pequeno (100 g)', 180, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Abacaxi', '1 fatia grande (100 g)', 49, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Acerola', '1 pequena (10 g)', 2, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ameixa fresca', '1 grande (50 g)', 27, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ameixa seca', '1 média (5 g)', 11, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Amora', '1 xícara', 50, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Banana-maçã', '1 média (65 g)', 72, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Banana-nanica', '1 média (70 g)', 67, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Banana-ouro', '1 pequena (30 g)', 31, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Banana-prata', '1 média (55 g)', 54, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cajá-manga', '1 médio (48 g)', 22, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Caju', '1 médio (50 g)', 23, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Caqui', '1 médio (52 g)', 36, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Carambola', '1 média (105 g)', 31, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cereja', '1 média (10 g)', 7, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Damasco seco', '1 médio (12 g)', 26, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Figo', '1 médio (70 g)', 46, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Framboesa', '1 xícara (100 g)', 57, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Goiaba', '1 média (95 g)', 48, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Jabuticaba', '4 unidades (20 g)', 10, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Jaca', '1 bago (12 g)', 9, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Kiwi', '1 médio (90 g)', 45, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Laranja', '1 média (130 g)', 60, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lichia', '4 unidades (100 g)', 65, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lima-da-pérsia', '1 média (95 g)', 51, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Limão', '1 médio (30 g)', 9, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Maçã', '1 média (140 g)', 81, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Maçã verde', '1 média (140 g)', 54, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mamão', '1 fatia média (100 g)', 36, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mamão papaia', '1/2 unidade (155 g)', 56, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Manga', '1/2 unidade (125 g)', 82, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Maracujá', '1 grande (90 g)', 40, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Melancia', '1 fatia média (200 g)', 50, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Melão', '1 fatia média (70 g)', 19, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Morango', '5 médios (50 g)', 20, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Nectarina', '1 grande (120 g)', 76, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Passas', '1 colher (sopa) (11 g)', 30, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pêra', '1 média (110 g)', 68, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pêssego', '1 pequeno (60 g)', 29, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salada de frutas', '1/2 xícara', 138, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tangerina', '1 média (100 g)', 45, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Uva', '1 média (5 g)', 8, 1);