INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Brie', '1 fatia média (22 g)', 57, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Camembert', '1 fatia média (25 g)', 68, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Catupiry', '1 colher (sopa)', 75, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cheddar', '1 fatia fina (15 g)', 63, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cottageintegral', '1 colher (sopa)', 37, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cottage desnatado', '1 colher (sopa)', 30, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cream cheese', '1 colher (sopa)', 105, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cream cheese light', '1 colher (sopa)', 62, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Emmental', '1 fatia pequena (35 g)', 140, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Gorgonzola', '1 fatia média (38 g)', 164, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Minas', '1 fatia média (30 g)', 73, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Minas light', '1 fatia média (30 g)', 46, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mussarela', '1 fatia fina (20 g)', 65, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mussarela de búfala', '1 unidade (45 g)', 74, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Parmesão ralado', '1 colher (sopa)', 27, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Polenguinho', '1 unidade (20 g)', 50, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Prato', '1 fatia fina (15 g)', 59, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Prato light', '1 fatia fina (15 g)', 35, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Provolone', '1 fatia fina (15 g)', 51, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Requeijão', '1 colher (sopa)', 86, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Requeijão light', '1 colher (sopa)', 57, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ricota', '1 fatia média (30 g)', 51, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ricota light', '1 fatia média (30 g)', 39, 6);