INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Coalhada', '1 colher (sopa) (20 g)', 52, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Creme de leite fresco', '1 colher (sopa)', 52, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Creme de leite light', '1 colher (sopa)', 26, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Danoninho', '1 unidade (45 g)', 66, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Iogurte desnatado', '1 unidade (200 ml)', 90, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Iogurte natural', '1 unidade (200 ml)', 154, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Leite condensado', '1 colher (sopa)', 49, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Leite condensado light', '1 colher (sopa)', 39, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Leite desnatado', '1 copo (200 ml)', 72, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Leite integral', '1 copo (200 ml)', 126, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Leite semidesnatado', '1 copo (200 ml)', 90, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Yakult', '1 unidade (80 g)', 51, 5);