INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cannelloni de frango', '1 unidade (50 g)', 97, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cannelloni de ricota', '1 unidade (55 g)', 135, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cappellettide carne', '1 xícara(100 g)', 282, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lasanha', '1 colher sopa (50 g)', 104, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Macarrão à bolonhesa', '1/2 xícara(115 g)', 142, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Macarrão cozido', '1/2 xícara (100 g)', 110, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Macarrão ao sugo', '1/2 xícara (100 g)', 102, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Macarrão com rúcula e queijo', '1/2xícara (80 g)', 262, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Nhoque ao sugo', '1 colher sopa (30 g)', 42, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Panqueca', '1 unidade (50 g)', 95, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Panqueca de carne', '1 unidade (80 g)', 228, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pizza calabresa (sem mussarela)', '1 fatia', 239, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pizza calabresa (com mussarela)', '1 fatia', 320, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pizza de mussarela', '1 fatia', 278, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pizza portuguesa', '1 fatia', 302, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Rolinho primavera', '1 unidade (60 g)', 95, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Quiche de queijo', '1 fatia (100 g)', 288, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Torta de camarão', '1 fatia (100 g)', 310, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Torta de frango', '1 fatia (120 g)', 282, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Torta de legumes', '1 fatia (100 g)', 241, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Torta de palmito', '1 fatia (100 g)', 260, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Torta de queijo', '1 fatia (100 g)', 320, 7);