INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ketchup', '1 colher (sopa)', 22, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho ao curry', '1 colher (sopa)', 31, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho branco', '1 colher (sopa)', 72, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho inglês', '1 colher (sopa)', 11, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho de iogurte', '1 colher (sopa)', 29, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho madeira', '1 colher (sopa)', 8, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho de pimenta', '1 colher (chá)', 2, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho para salada italiano', '1 colher (chá)', 48, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho tártaro', '1 colher (sopa)', 75, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho de tomate refogado', '4 colheres (sopa)', 57, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mostarda', '1 colher (sopa)', 11, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Shoyu', '1 colher (sopa)', 7, 15);