INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Açúcar', '1 colher (sopa)', 40, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bala', '1 unidade (5 g)', 20, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Barra de cereais (de banana)', '1 unidade (25 g)', 90, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Batom Garoto', '1 unidade (16g)', 66, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Beijinho', '1 unidade (30 g)', 105, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bis', '1 unidade (7,5 g)', 39, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bolo comum', '1 fatia (60 g)', 215, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bolo diet', '1 fatia (60 g)', 129, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bombom Alpino', '1 unidade (13g)', 69, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bombom com cereja', '1 unidade (21 g)', 99, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bombom Serenata de Amor', '1 unidade (20g)', 88, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bombom Sonho de Valsa', '1 unidade (21,5 g)', 115, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Brigadeiro', '1 unidade (30 g)', 121, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cereja em calda', '1 colher (sobremesa)', 39, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chiclete', '1 unidade(4 g)', 14, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chocolate', 'tablete de 30 g', 150, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Creme de papaia', '1 taça (150 g)', 260, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frozen iogurte', '1 porção (200 g)', 115, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frutas em calda', '1/2 xícara (60 g)', 110, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Gelatina diet', '1 taça (100 g)', 15, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Geléia', '1 colher (sopa)', 50, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Goiabada', '1 colher (sopa)', 40, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mel', '1 colher (sopa)', 30, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Milk-shake de chocolate', '1 copo (250 ml)', 575, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Milk-shake de morango', '1 copo (250 ml)', 379, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('M&M chocolate', '1 pacote (30 g)', 134, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Musse de maracujá ', '1 taça (150 g)', 304, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Musse de chocolate', '1 taça (150 g)', 333, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Panetone', '1 fatia pequena (45 g)', 122, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sorvete à base de fruta ', '1 picolé', 60, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sorvete cremoso', '1 colher (sopa)', 63, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sorvete dietchocolate', '1 colher (sopa)', 44, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sorvete diet frutas ', '1 colher (sopa)', 31, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sundae ', '1 pequeno (250 g)', 265, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Suspiro ', '1 unidade (10 g)', 38, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tortas doces', '1 fatia pequena (70 g)', 390, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Trufa de chocolate', '1 unidade (30g)', 121, 10);