INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Blanquete de peru', '1 fatia fina (10 g)', 13, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chester assado', '1 pedaço médio (60 g)', 98, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Estrogonofe de frango', '1 concha', 338, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Filé de frango à milanesa', '1 médio (100 g)', 287, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Filé de frango grelhado', '1 médio (100 g)', 97, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Filé de frango frito', '1 médio (100 g)', 145, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frango assado', 'coxa média (40 g)', 49, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frango assado', 'peito (100 g)', 109, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frango assado', 'sobrecoxa (65 g)', 78, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frango ensopado desfiado', '1 colher (sopa)', 26, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frango xadrez', '1 concha', 70, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Hambúrguer de frango (sem o pão)', '1 unidade (56 g)', 130, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Hambúrguer de peru (sem o pão)', '1 unidade (90 g)', 133, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Peito de frango defumado', '1 fatia (30 g)', 29, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Peito de peru defumado light', '1 fatia (15 g)', 15, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Peito de peru assado', '1 fatia grande (100 g)', 162, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Peru assado, carne escura', '1 pedaço (100 g)', 218, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salsicha de frango ou chester', '1 unidade (50 g)', 106, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salsicha de peru', '1 unidade (50 g)', 65, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Omelete', '1 ovo', 110, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ovo de codorna', '1 unidade', 16, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ovo de galinha cozido', '1 médio', 71, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ovo frito', '1 médio', 105, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ovo mexido', '1 colher (sopa)', 29, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Almôndega', '1 unidade (50 g)', 102, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bife à milanesa', '1 pequeno (100 g)', 287, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bife frito', '1 médio (100 g)', 248, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bife na chapa', '1 médio (100 g)', 203, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bife à parmigiana', '1 pequeno (100 g)', 369, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bife rolê', '1 pequeno (100 g)', 224, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Carne assada', '1 fatia média (100 g)', 288, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Carne ensopada', '1 colher (sopa) (50 g)', 56, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Carne moída', '4 colheres (sopa)(100 g)', 213, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Carne-seca', '1 pedaço médio (65 g)', 279, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Carpaccio com molho de <br />limão, mostarda e alcaparras', '1 prato (95 g)', 90, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Costela de boi assada', '1 pedaço médio (65 g)', 181, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Churrasco (maminha, picanha)', '(100 g)', 250, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Estrogonofe de carne', '1 concha (170 g)', 294, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Fígado frito', '1 bife médio (100 g)', 216, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Fraldinha assada', '1 fatia (100 g)', 185, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Hambúrguer (sem o pão)', '1 unidade (80 g)', 160, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Rosbife', '1 fatia fina (45 g)', 72, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bacon', '1 fatia (15 g)', 99, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Costela de porco', '1 pedaço pequeno (23 g)', 102, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lingüiça calabresa frita', '1 unidade (40 g)', 120, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lombo de porco assado', '1 fatia (80 g)', 242, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mortadela', '1 fatia fina (15 g)', 41, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Porco agridoce', '1 colher grande (80 g)', 277, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Presunto cru ', '1 fatia (15 g)', 30, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Presunto cozido', '1 fatia (15 g)', 25, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tender assado', '1 fatia média (50 g)', 82, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salame', '1 fatia fina (2,5 g)', 11, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salsicha', '1 unidade (50 g)', 146, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salsichão', '1 fatia (10 g)', 45, 3);