INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Acarajé', '1 unidade média', 169, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Azeitona', '1 unidade média', 11, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bolinho de bacalhau', '1 unidade média', 80, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Casquinha de siri', '1 unidade média', 380, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Coxinha de frango', '1 unidade grande', 400, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Croquete de carne', '1 unidade pequena', 87, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Croquete de carne', '1 unidade grande', 346, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Empadinha', '1 unidade ', 108, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Empanada de carne', '1 unidade', 234, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Esfiha de carne', '1 unidade média ', 206, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Esfiha de queijo', '1 unidade média', 238, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Folheado de presunto', '1 unidade', 370, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pastel de carne', '1 unidade grande', 324, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pastel de queijo', '1 unidade grande', 361, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Quibe', '1 unidade grande grande', 318, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Risole de carne', '1 unidade média', 149, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sushi califórnia', '1 unidade', 32, 11);