INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Arroz à grega', '1 colher (sopa)', 35, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Arroz branco cozido', '1 colher (sopa)', 41, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Arroz chop-suey', '1 colher (sopa)', 43, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Arroz-de-carreteiro', '1 colher (sopa)', 63, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Arroz integral cozido', '1 colher (sopa)', 54, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Aveia em flocos', '1 colher (sopa)', 26, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Baked potato com requeijão light', '1 unidade', 305, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Batata cozida', '1 unidade média (90 g)', 76, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Batata-doce cozida', '1 fatia média (70 g)', 72, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Batata frita', '1 prato sobremesa (200 g)', 545, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Batata sauté', '1 colher (sopa)', 38, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cereal tipo All-Bran', '1 colher (sopa)', 23, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Corn Flakes', '1 colher (sopa)', 15, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Creme de milho', '1 colher (sopa)', 35, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Farinha de mandioca', '1 colher (sopa)', 57, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Farofa', '1 colher (sopa)', 71, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Feijão', '1 colher (sopa)', 12, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Granola', '1 colher (sopa)', 28, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Grão-de-bico', '1 colher (sopa)', 26, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lentilha', '1 colher (sopa)', 19, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mandioca frita', '1 pedaço pequeno (50 g)', 176, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mandioca cozida', '1 pedaço médio (90 g)', 108, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pipoca', '1 saco pequeno (60 g)', 240, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Polenta cozida', '1 fatia (100 g)', 172, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Polenta frita', '1 quadrado (50 g)', 184, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Purê de batata', '1 colher (sopa)', 56, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salada de batata com maionese', '1 colher (sopa)', 53, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salada de feijão-fradinho', '1 colher (sopa)', 51, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sopa de ervilha', '1 concha média (130 g)', 169, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sopa de feijão com macarrão', '1 concha média (160 g)', 211, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tofu (queijo de soja)', '1 fatia média(30 g)', 60, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tutu de feijão', '1 colher (sopa) (30 g)', 34, 8);