INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Baguete (pequena)', '1 unidade (55 g)', 156, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Biscoito de fibras', '1 unidade', 36, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Biscoito doce', '1 unidade', 27, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Biscoito recheado', '1 unidade', 64, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Biscoito waffle', '1 unidade', 47, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bisnaguinha', '1 unidade (30 g)', 59, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ciabatta(pequena)', '1 unidade (70 g)', 160, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cookie de chocolate', '1 unidade (10 g)', 48, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cream cracker, água e sal', '1 unidade (8 g)', 32, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Croissant', '1 unidade (40 g)', 165, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Muffin', '1 unidade (45 g)', 173, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão de batata', '1 unidade', 165, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão de fôrma', '1 fatia', 68, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão francês', '1 unidade', 134, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão francês sem miolo', '1 unidade', 81, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão de glúten, centeio', '1 fatia', 72, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão light', '1 fatia', 52, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão sírio', '1 unidade média', 160, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão italiano', '1 fatia média', 85, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão de queijo', '1 grande', 173, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Stick', '1 unidade (3 g)', 4, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Torrada', '1 unidade (12 g)', 36, 9);