INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Abóbora', '1 xícara', 49, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Abobrinha', '1 xícara', 24, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Acelga ', '1 xícara', 13, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Agrião', '1 xícara', 6, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Aipo (salsão)', '1 xícara', 20, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Alcachofra', '1 unidade (80 g)', 61, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Alface', '1 folha', 6, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Almeirão', '1 xícara', 8, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Berinjela', '1 xícara', 28, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bertalha', '1 xícara', 6, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Beterraba', '1 xícara', 40, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Brócolis', '1 xícara', 18, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Broto de feijão', '1 xícara', 43, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cebola', '1 xícara', 30, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cenoura', '1 xícara', 31, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chicória', '1 xícara', 9, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chuchu', '1 xícara', 25, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cogumelo', '1 xícara', 29, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Couve', '1 xícara', 14, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Couve-de-bruxelas', '1 xícara', 46, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Couve-flor', '1 xícara', 21, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Endívia', '1 xícara', 14, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Erva-doce (funcho)', '1 xícara', 20, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ervilha (vagem)', '1 xícara', 45, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Erviha em conserva', '1 xícara', 110, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Escarola', '1 xícara', 9, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Espinafre', '1 xícara', 14, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Jiló', '1 xícara', 57, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Milho verde', '1 xícara', 130, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Nabo', '1 xícara', 11, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Palmito', '1 xícara', 38, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pepino', '1 xícara', 12, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Picles em conserva', '1 xícara', 20, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pimentão', '1 xícara', 26, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Rabanete', '1 xícara', 12, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Repolho', '1 xícara', 13, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Rúcula', '1 xícara', 10, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Quiabo', '1 xícara', 36, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Seleta de legumes', '1 xícara', 45, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tomate', '1 unidade', 26, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Vagem', '1 xícara', 77, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Babaganuche (pasta de berinjela)', '1 colher (sopa)', 74, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Berinjela frita', '1 colher (sopa)', 55, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chucrute', '1 xícara', 33, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Couve-flor à milanesa', '1 colher (sopa)', 38, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Espinafre ao creme', '1 colher (sopa)', 34, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Gaspacho', '1 prato (300 ml)', 120, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salada de legumes com maionese', '1 colher (sopa)', 25, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sopa de cebola', '1 prato (300 ml)', 134, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sopa de legumes', '1 prato (300 ml)', 231, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sopa de tomate', '1 prato (300 ml)', 164, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tomate seco', '1 unidade', 45, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tabule', '1 colher (sopa)', 52, 2);