INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Abacate', '1/2 pequeno (100 g)', 180, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Abacaxi', '1 fatia grande (100 g)', 49, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Acerola', '1 pequena (10 g)', 2, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ameixa fresca', '1 grande (50 g)', 27, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ameixa seca', '1 média (5 g)', 11, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Amora', '1 xícara', 50, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Banana-maçã', '1 média (65 g)', 72, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Banana-nanica', '1 média (70 g)', 67, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Banana-ouro', '1 pequena (30 g)', 31, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Banana-prata', '1 média (55 g)', 54, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cajá-manga', '1 médio (48 g)', 22, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Caju', '1 médio (50 g)', 23, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Caqui', '1 médio (52 g)', 36, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Carambola', '1 média (105 g)', 31, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cereja', '1 média (10 g)', 7, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Damasco seco', '1 médio (12 g)', 26, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Figo', '1 médio (70 g)', 46, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Framboesa', '1 xícara (100 g)', 57, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Goiaba', '1 média (95 g)', 48, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Jabuticaba', '4 unidades (20 g)', 10, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Jaca', '1 bago (12 g)', 9, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Kiwi', '1 médio (90 g)', 45, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Laranja', '1 média (130 g)', 60, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lichia', '4 unidades (100 g)', 65, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lima-da-pérsia', '1 média (95 g)', 51, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Limão', '1 médio (30 g)', 9, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Maçã', '1 média (140 g)', 81, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Maçã verde', '1 média (140 g)', 54, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mamão', '1 fatia média (100 g)', 36, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mamão papaia', '1/2 unidade (155 g)', 56, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Manga', '1/2 unidade (125 g)', 82, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Maracujá', '1 grande (90 g)', 40, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Melancia', '1 fatia média (200 g)', 50, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Melão', '1 fatia média (70 g)', 19, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Morango', '5 médios (50 g)', 20, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Nectarina', '1 grande (120 g)', 76, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Passas', '1 colher (sopa) (11 g)', 30, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pêra', '1 média (110 g)', 68, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pêssego', '1 pequeno (60 g)', 29, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salada de frutas', '1/2 xícara', 138, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tangerina', '1 média (100 g)', 45, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Uva', '1 média (5 g)', 8, 1);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Abóbora', '1 xícara', 49, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Abobrinha', '1 xícara', 24, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Acelga ', '1 xícara', 13, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Agrião', '1 xícara', 6, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Aipo (salsão)', '1 xícara', 20, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Alcachofra', '1 unidade (80 g)', 61, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Alface', '1 folha', 6, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Almeirão', '1 xícara', 8, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Berinjela', '1 xícara', 28, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bertalha', '1 xícara', 6, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Beterraba', '1 xícara', 40, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Brócolis', '1 xícara', 18, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Broto de feijão', '1 xícara', 43, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cebola', '1 xícara', 30, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cenoura', '1 xícara', 31, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chicória', '1 xícara', 9, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chuchu', '1 xícara', 25, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cogumelo', '1 xícara', 29, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Couve', '1 xícara', 14, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Couve-de-bruxelas', '1 xícara', 46, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Couve-flor', '1 xícara', 21, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Endívia', '1 xícara', 14, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Erva-doce (funcho)', '1 xícara', 20, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ervilha (vagem)', '1 xícara', 45, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Erviha em conserva', '1 xícara', 110, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Escarola', '1 xícara', 9, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Espinafre', '1 xícara', 14, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Jiló', '1 xícara', 57, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Milho verde', '1 xícara', 130, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Nabo', '1 xícara', 11, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Palmito', '1 xícara', 38, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pepino', '1 xícara', 12, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Picles em conserva', '1 xícara', 20, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pimentão', '1 xícara', 26, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Rabanete', '1 xícara', 12, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Repolho', '1 xícara', 13, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Rúcula', '1 xícara', 10, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Quiabo', '1 xícara', 36, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Seleta de legumes', '1 xícara', 45, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tomate', '1 unidade', 26, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Vagem', '1 xícara', 77, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Babaganuche (pasta de berinjela)', '1 colher (sopa)', 74, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Berinjela frita', '1 colher (sopa)', 55, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chucrute', '1 xícara', 33, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Couve-flor à milanesa', '1 colher (sopa)', 38, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Espinafre ao creme', '1 colher (sopa)', 34, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Gaspacho', '1 prato (300 ml)', 120, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salada de legumes com maionese', '1 colher (sopa)', 25, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sopa de cebola', '1 prato (300 ml)', 134, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sopa de legumes', '1 prato (300 ml)', 231, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sopa de tomate', '1 prato (300 ml)', 164, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tomate seco', '1 unidade', 45, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tabule', '1 colher (sopa)', 52, 2);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Blanquete de peru', '1 fatia fina (10 g)', 13, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chester assado', '1 pedaço médio (60 g)', 98, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Estrogonofe de frango', '1 concha', 338, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Filé de frango à milanesa', '1 médio (100 g)', 287, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Filé de frango grelhado', '1 médio (100 g)', 97, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Filé de frango frito', '1 médio (100 g)', 145, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frango assado', 'coxa média (40 g)', 49, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frango assado', 'peito (100 g)', 109, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frango assado', 'sobrecoxa (65 g)', 78, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frango ensopado desfiado', '1 colher (sopa)', 26, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frango xadrez', '1 concha', 70, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Hambúrguer de frango (sem o pão)', '1 unidade (56 g)', 130, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Hambúrguer de peru (sem o pão)', '1 unidade (90 g)', 133, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Peito de frango defumado', '1 fatia (30 g)', 29, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Peito de peru defumado light', '1 fatia (15 g)', 15, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Peito de peru assado', '1 fatia grande (100 g)', 162, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Peru assado, carne escura', '1 pedaço (100 g)', 218, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salsicha de frango ou chester', '1 unidade (50 g)', 106, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salsicha de peru', '1 unidade (50 g)', 65, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Omelete', '1 ovo', 110, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ovo de codorna', '1 unidade', 16, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ovo de galinha cozido', '1 médio', 71, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ovo frito', '1 médio', 105, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ovo mexido', '1 colher (sopa)', 29, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Almôndega', '1 unidade (50 g)', 102, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bife à milanesa', '1 pequeno (100 g)', 287, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bife frito', '1 médio (100 g)', 248, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bife na chapa', '1 médio (100 g)', 203, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bife à parmigiana', '1 pequeno (100 g)', 369, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bife rolê', '1 pequeno (100 g)', 224, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Carne assada', '1 fatia média (100 g)', 288, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Carne ensopada', '1 colher (sopa) (50 g)', 56, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Carne moída', '4 colheres (sopa)(100 g)', 213, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Carne-seca', '1 pedaço médio (65 g)', 279, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Carpaccio com molho de limão, mostarda e alcaparras', '1 prato (95 g)', 90, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Costela de boi assada', '1 pedaço médio (65 g)', 181, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Churrasco (maminha, picanha)', '(100 g)', 250, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Estrogonofe de carne', '1 concha (170 g)', 294, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Fígado frito', '1 bife médio (100 g)', 216, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Fraldinha assada', '1 fatia (100 g)', 185, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Hambúrguer (sem o pão)', '1 unidade (80 g)', 160, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Rosbife', '1 fatia fina (45 g)', 72, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bacon', '1 fatia (15 g)', 99, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Costela de porco', '1 pedaço pequeno (23 g)', 102, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lingüiça calabresa frita', '1 unidade (40 g)', 120, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lombo de porco assado', '1 fatia (80 g)', 242, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mortadela', '1 fatia fina (15 g)', 41, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Porco agridoce', '1 colher grande (80 g)', 277, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Presunto cru ', '1 fatia (15 g)', 30, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Presunto cozido', '1 fatia (15 g)', 25, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tender assado', '1 fatia média (50 g)', 82, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salame', '1 fatia fina (2,5 g)', 11, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salsicha', '1 unidade (50 g)', 146, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salsichão', '1 fatia (10 g)', 45, 3);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Atum em óleo', '1 lata (160 g)', 448, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Atum em água', '1 lata (160 g)', 184, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bacalhau assado', '1 posta (100 g)', 110, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Camarão cozido', '5 grandes(100 g)', 82, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Camarão frito', '10 médios (100 g)', 310, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Estrogonofe de camarão', '1 concha', 338, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Filé de peixe grelhado', '1 médio (120 g)', 120, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Filé de peixe à milanesa e molho de camarão', '1 médio (100g)', 383, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Kani kama', '1 stick (16 g)', 13, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lagosta grelhada na manteiga', '1 unidade (200 g)', 308, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lula cozida', '1/2 concha (100 g)', 93, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lula frita', '4 colheres (sopa) (100 g)', 190, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mariscos ao vinagrete', '1 prato (sobremesa) ', 82, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mexilhão cozido', '8 grandes (100 g)', 80, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ostras', '6 médias (100 g)', 60, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Peixe à escabeche', '1 filé médio (100 g)', 183, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Peixe ensopado', '1 concha (100 g)', 130, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pintado na brasa', '1 pedaço médio (80 g)', 134, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Polvo refogado', '1 colher (sopa) (22 g)', 18, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salmão defumado', '1 filé fino (50 g)', 75, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salmão cozido ou grelhado ', '1 filé (120 g)', 240, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sardinha em conserva (molho de tomate)', '1 unidade (25 g)', 45, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sardinha (no azeite)', '1 unidade (33 g)', 98, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sardinha frita', '1 unidade (40 g)', 91, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sashimi (variado)', '1 porção (100 g)', 80, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Truta assada ou cozida', '1/2 unidade (120 g)', 162, 4);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Coalhada', '1 colher (sopa) (20 g)', 52, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Creme de leite fresco', '1 colher (sopa)', 52, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Creme de leite light', '1 colher (sopa)', 26, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Danoninho', '1 unidade (45 g)', 66, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Iogurte desnatado', '1 unidade (200 ml)', 90, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Iogurte natural', '1 unidade (200 ml)', 154, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Leite condensado', '1 colher (sopa)', 49, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Leite condensado light', '1 colher (sopa)', 39, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Leite desnatado', '1 copo (200 ml)', 72, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Leite integral', '1 copo (200 ml)', 126, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Leite semidesnatado', '1 copo (200 ml)', 90, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Yakult', '1 unidade (80 g)', 51, 5);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Brie', '1 fatia média (22 g)', 57, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Camembert', '1 fatia média (25 g)', 68, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Catupiry', '1 colher (sopa)', 75, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cheddar', '1 fatia fina (15 g)', 63, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cottageintegral', '1 colher (sopa)', 37, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cottage desnatado', '1 colher (sopa)', 30, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cream cheese', '1 colher (sopa)', 105, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cream cheese light', '1 colher (sopa)', 62, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Emmental', '1 fatia pequena (35 g)', 140, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Gorgonzola', '1 fatia média (38 g)', 164, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Minas', '1 fatia média (30 g)', 73, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Minas light', '1 fatia média (30 g)', 46, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mussarela', '1 fatia fina (20 g)', 65, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mussarela de búfala', '1 unidade (45 g)', 74, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Parmesão ralado', '1 colher (sopa)', 27, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Polenguinho', '1 unidade (20 g)', 50, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Prato', '1 fatia fina (15 g)', 59, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Prato light', '1 fatia fina (15 g)', 35, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Provolone', '1 fatia fina (15 g)', 51, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Requeijão', '1 colher (sopa)', 86, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Requeijão light', '1 colher (sopa)', 57, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ricota', '1 fatia média (30 g)', 51, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ricota light', '1 fatia média (30 g)', 39, 6);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cannelloni de frango', '1 unidade (50 g)', 97, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cannelloni de ricota', '1 unidade (55 g)', 135, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cappellettide carne', '1 xícara(100 g)', 282, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lasanha', '1 colher sopa (50 g)', 104, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Macarrão à bolonhesa', '1/2 xícara(115 g)', 142, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Macarrão cozido', '1/2 xícara (100 g)', 110, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Macarrão ao sugo', '1/2 xícara (100 g)', 102, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Macarrão com rúcula e queijo', '1/2xícara (80 g)', 262, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Nhoque ao sugo', '1 colher sopa (30 g)', 42, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Panqueca', '1 unidade (50 g)', 95, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Panqueca de carne', '1 unidade (80 g)', 228, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pizza calabresa (sem mussarela)', '1 fatia', 239, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pizza calabresa (com mussarela)', '1 fatia', 320, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pizza de mussarela', '1 fatia', 278, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pizza portuguesa', '1 fatia', 302, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Rolinho primavera', '1 unidade (60 g)', 95, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Quiche de queijo', '1 fatia (100 g)', 288, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Torta de camarão', '1 fatia (100 g)', 310, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Torta de frango', '1 fatia (120 g)', 282, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Torta de legumes', '1 fatia (100 g)', 241, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Torta de palmito', '1 fatia (100 g)', 260, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Torta de queijo', '1 fatia (100 g)', 320, 7);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Arroz à grega', '1 colher (sopa)', 35, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Arroz branco cozido', '1 colher (sopa)', 41, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Arroz chop-suey', '1 colher (sopa)', 43, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Arroz-de-carreteiro', '1 colher (sopa)', 63, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Arroz integral cozido', '1 colher (sopa)', 54, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Aveia em flocos', '1 colher (sopa)', 26, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Baked potato com requeijão light', '1 unidade', 305, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Batata cozida', '1 unidade média (90 g)', 76, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Batata-doce cozida', '1 fatia média (70 g)', 72, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Batata frita', '1 prato sobremesa (200 g)', 545, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Batata sauté', '1 colher (sopa)', 38, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cereal tipo All-Bran', '1 colher (sopa)', 23, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Corn Flakes', '1 colher (sopa)', 15, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Creme de milho', '1 colher (sopa)', 35, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Farinha de mandioca', '1 colher (sopa)', 57, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Farofa', '1 colher (sopa)', 71, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Feijão', '1 colher (sopa)', 12, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Granola', '1 colher (sopa)', 28, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Grão-de-bico', '1 colher (sopa)', 26, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Lentilha', '1 colher (sopa)', 19, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mandioca frita', '1 pedaço pequeno (50 g)', 176, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mandioca cozida', '1 pedaço médio (90 g)', 108, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pipoca', '1 saco pequeno (60 g)', 240, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Polenta cozida', '1 fatia (100 g)', 172, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Polenta frita', '1 quadrado (50 g)', 184, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Purê de batata', '1 colher (sopa)', 56, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salada de batata com maionese', '1 colher (sopa)', 53, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salada de feijão-fradinho', '1 colher (sopa)', 51, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sopa de ervilha', '1 concha média (130 g)', 169, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sopa de feijão com macarrão', '1 concha média (160 g)', 211, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tofu (queijo de soja)', '1 fatia média(30 g)', 60, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tutu de feijão', '1 colher (sopa) (30 g)', 34, 8);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Baguete (pequena)', '1 unidade (55 g)', 156, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Biscoito de fibras', '1 unidade', 36, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Biscoito doce', '1 unidade', 27, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Biscoito recheado', '1 unidade', 64, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Biscoito waffle', '1 unidade', 47, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bisnaguinha', '1 unidade (30 g)', 59, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ciabatta(pequena)', '1 unidade (70 g)', 160, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cookie de chocolate', '1 unidade (10 g)', 48, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cream cracker, água e sal', '1 unidade (8 g)', 32, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Croissant', '1 unidade (40 g)', 165, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Muffin', '1 unidade (45 g)', 173, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão de batata', '1 unidade', 165, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão de fôrma', '1 fatia', 68, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão francês', '1 unidade', 134, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão francês sem miolo', '1 unidade', 81, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão de glúten, centeio', '1 fatia', 72, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão light', '1 fatia', 52, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão sírio', '1 unidade média', 160, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão italiano', '1 fatia média', 85, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pão de queijo', '1 grande', 173, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Stick', '1 unidade (3 g)', 4, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Torrada', '1 unidade (12 g)', 36, 9);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Açúcar', '1 colher (sopa)', 40, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bala', '1 unidade (5 g)', 20, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Barra de cereais (de banana)', '1 unidade (25 g)', 90, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Batom Garoto', '1 unidade (16g)', 66, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Beijinho', '1 unidade (30 g)', 105, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bis', '1 unidade (7,5 g)', 39, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bolo comum', '1 fatia (60 g)', 215, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bolo diet', '1 fatia (60 g)', 129, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bombom Alpino', '1 unidade (13g)', 69, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bombom com cereja', '1 unidade (21 g)', 99, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bombom Serenata de Amor', '1 unidade (20g)', 88, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bombom Sonho de Valsa', '1 unidade (21,5 g)', 115, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Brigadeiro', '1 unidade (30 g)', 121, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cereja em calda', '1 colher (sobremesa)', 39, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chiclete', '1 unidade(4 g)', 14, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chocolate', 'tablete de 30 g', 150, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Creme de papaia', '1 taça (150 g)', 260, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frozen iogurte', '1 porção (200 g)', 115, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Frutas em calda', '1/2 xícara (60 g)', 110, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Gelatina diet', '1 taça (100 g)', 15, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Geléia', '1 colher (sopa)', 50, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Goiabada', '1 colher (sopa)', 40, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mel', '1 colher (sopa)', 30, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Milk-shake de chocolate', '1 copo (250 ml)', 575, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Milk-shake de morango', '1 copo (250 ml)', 379, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('M&M chocolate', '1 pacote (30 g)', 134, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Musse de maracujá ', '1 taça (150 g)', 304, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Musse de chocolate', '1 taça (150 g)', 333, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Panetone', '1 fatia pequena (45 g)', 122, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sorvete à base de fruta ', '1 picolé', 60, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sorvete cremoso', '1 colher (sopa)', 63, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sorvete dietchocolate', '1 colher (sopa)', 44, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sorvete diet frutas ', '1 colher (sopa)', 31, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sundae ', '1 pequeno (250 g)', 265, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Suspiro ', '1 unidade (10 g)', 38, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Tortas doces', '1 fatia pequena (70 g)', 390, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Trufa de chocolate', '1 unidade (30g)', 121, 10);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Acarajé', '1 unidade média', 169, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Azeitona', '1 unidade média', 11, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bolinho de bacalhau', '1 unidade média', 80, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Casquinha de siri', '1 unidade média', 380, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Coxinha de frango', '1 unidade grande', 400, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Croquete de carne', '1 unidade pequena', 87, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Croquete de carne', '1 unidade grande', 346, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Empadinha', '1 unidade ', 108, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Empanada de carne', '1 unidade', 234, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Esfiha de carne', '1 unidade média ', 206, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Esfiha de queijo', '1 unidade média', 238, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Folheado de presunto', '1 unidade', 370, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pastel de carne', '1 unidade grande', 324, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pastel de queijo', '1 unidade grande', 361, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Quibe', '1 unidade grande grande', 318, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Risole de carne', '1 unidade média', 149, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Sushi califórnia', '1 unidade', 32, 11);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bauru', '1 unidade', 410, 12);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Big Mac', '1 unidade', 590, 12);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Beirute completo', '1 unidade ', 490, 12);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Beirute de peito de peru', '1 unidade ', 295, 12);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cachorro quente', '1 unidade', 330, 12);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cheeseburger McDonalds', '1 unidade', 358, 12);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Hambúrguer', '1 unidade', 290, 12);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Misto-quente', '1 unidade', 370, 12);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Bobó de camarão', '1 colher (sopa)', 46, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Canja', '1 concha', 110, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cuscuz à paulista', '1 fatia média (100 g)', 328, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Dobradinha', '1 colher (sopa)', 39, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Feijoada', '1 concha', 346, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Goulash', '1 colher grande (90 g)', 186, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Moqueca de camarão', '1 concha', 320, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Moqueca de peixe', '1 concha', 290, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Paella', '1 colher grande (90 g)', 180, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Pimentão assado recheado com carne moída', '1 unidade (200 g)', 298, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Risoto de frango', '1 colher (sopa)', 63, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Risoto de funghi', '1 colher (sopa)', 78, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Salpicão de frango', '1 colher (sopa)', 47, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Suflê de espinafre', '1 colher (sopa)', 45, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Suflê de legumes', '1 colher (sopa)', 38, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Suflê de queijo', '1 colher (sopa)', 55, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Vatapá', '1 colher grande (90 g)', 320, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Yakissoba', '1 colher grande (75 g)', 112, 13);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Azeite e outros óleos', '1 colher (chá)', 72, 14);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Maionese', '1 colher (chá)', 53, 14);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Maionese light', '1 colher (chá)', 27, 14);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Manteiga e margarina', '1 colher (chá)', 60 , 14);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Margarina light', '1 colher (chá)', 29, 14);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Ketchup', '1 colher (sopa)', 22, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho ao curry', '1 colher (sopa)', 31, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho branco', '1 colher (sopa)', 72, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho inglês', '1 colher (sopa)', 11, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho de iogurte', '1 colher (sopa)', 29, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho madeira', '1 colher (sopa)', 8, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho de pimenta', '1 colher (chá)', 2, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho para salada italiano', '1 colher (chá)', 48, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho tártaro', '1 colher (sopa)', 75, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Molho de tomate refogado', '4 colheres (sopa)', 57, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Mostarda', '1 colher (sopa)', 11, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Shoyu', '1 colher (sopa)', 7, 15);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Água-de-coco', '1 copo (200 ml)', 40, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Caipirinha', '1 copo (100 ml)', 260, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Cerveja', '1 lata(350 ml)', 147, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chá diet', '1 copo (200 ml)', 3, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Champanhe seco', '1 taça (120)', 85, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Chope', '1 copo (300 ml)', 126 , 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Coquetel de frutas', '1 copo (100 ml)', 80, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Licor ', '1 cálice (50 ml)', 170, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Refrigerante diet ', '1 copo (200 ml)', 3, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Refrigerante normal', '1 copo (200 ml)', 115, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Prosecco', '1 taça (120 ml)', 85, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Suco de laranja ', '1 copo (250 ml)', 160, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Uísque ou vodca ', '1 dose (50 ml)', 108, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Vinho branco seco', '1 taça (120 ml)', 90, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Vinho branco doce', '1 taça (120)', 170, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Vinho tinto seco', '1 taça (120 ml)', 110, 16);
INSERT INTO alimentos(nome, porcao, calorias, cod_categoria) VALUES('Vitamina de frutas com leite', '1 copo (250 ml)', 95, 16);